name: SimpleChestShopRU
version: 1.1.0
main: ru.alex.shop.SimpleChestShopPlugin
api-version: '1.21'
author: alex
description: Chest shop plugin (RU)

permissions:
  simplechestshop.create:
    default: true
  simplechestshop.use:
    default: true
  simplechestshop.admin:
    default: op
