name: SimpleChestShopRU
version: 1.4.1
main: ru.alex.shop.SimpleChestShopPlugin
api-version: '1.21'

commands:
  shop:
    usage: /shop set <price> <amount> | /shop refresh
    description: Chest shop commands

permissions:
  simplechestshop.set:
    default: true
  simplechestshop.admin:
    default: op
